apiVersion: apps/v1
kind: Deployment
metadata:
  name: keydb-deployment
  labels:
    app: keydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keydb
  template:
    metadata:
      labels:
        app: keydb
    spec:
      containers:
      - name: keydb
        image: eqalpha/keydb
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2ptrackerd-deployment
  labels:
    app: p2ptrackerd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p2ptrackerd
  template:
    metadata:
      labels:
        app: p2ptrackerd
    spec:
      containers:
      - name: p2p
        image: docker.pkg.github.com/dawidd6/p2p/p2p
        ports:
        - containerPort: 8080
        command: ["p2ptrackerd"]
        args: ["--host=0.0.0.0", "--port=8080", "--db-host=keydb-service", "--db-port=6379"]
---
apiVersion: v1
kind: Service
metadata:
  name: keydb-service
  labels:
    app: keydb
spec:
  selector:
    app: keydb
  ports:
  - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: p2ptrackerd-service
  labels:
    app: p2ptrackerd
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: p2ptrackerd
  ports:
  - port: 8080
