// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: seed/seed.proto

package seed

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TorrentFileSha256 string `protobuf:"bytes,2,opt,name=torrent_file_sha256,json=torrentFileSha256,proto3" json:"torrent_file_sha256,omitempty"`
	FileName          string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	PieceNumber       uint64 `protobuf:"varint,4,opt,name=piece_number,json=pieceNumber,proto3" json:"piece_number,omitempty"`
}

func (x *SeedRequest) Reset() {
	*x = SeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_seed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedRequest) ProtoMessage() {}

func (x *SeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seed_seed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedRequest.ProtoReflect.Descriptor instead.
func (*SeedRequest) Descriptor() ([]byte, []int) {
	return file_seed_seed_proto_rawDescGZIP(), []int{0}
}

func (x *SeedRequest) GetTorrentFileSha256() string {
	if x != nil {
		return x.TorrentFileSha256
	}
	return ""
}

func (x *SeedRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SeedRequest) GetPieceNumber() uint64 {
	if x != nil {
		return x.PieceNumber
	}
	return 0
}

type SeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PieceData []byte `protobuf:"bytes,1,opt,name=piece_data,json=pieceData,proto3" json:"piece_data,omitempty"`
}

func (x *SeedResponse) Reset() {
	*x = SeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seed_seed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedResponse) ProtoMessage() {}

func (x *SeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seed_seed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedResponse.ProtoReflect.Descriptor instead.
func (*SeedResponse) Descriptor() ([]byte, []int) {
	return file_seed_seed_proto_rawDescGZIP(), []int{1}
}

func (x *SeedResponse) GetPieceData() []byte {
	if x != nil {
		return x.PieceData
	}
	return nil
}

var File_seed_seed_proto protoreflect.FileDescriptor

var file_seed_seed_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x65, 0x65, 0x64, 0x2f, 0x73, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7d, 0x0a, 0x0b, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2e, 0x0a, 0x13, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x74,
	0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x32, 0x35, 0x36,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x70, 0x69, 0x65, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x70, 0x69, 0x65, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x2d, 0x0a, 0x0c, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x69, 0x65, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x69, 0x65, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x32,
	0x2f, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x64, 0x12,
	0x0c, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x53, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x61, 0x77, 0x69, 0x64, 0x64, 0x36, 0x2f, 0x70, 0x32, 0x70, 0x2f, 0x73, 0x65, 0x65, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seed_seed_proto_rawDescOnce sync.Once
	file_seed_seed_proto_rawDescData = file_seed_seed_proto_rawDesc
)

func file_seed_seed_proto_rawDescGZIP() []byte {
	file_seed_seed_proto_rawDescOnce.Do(func() {
		file_seed_seed_proto_rawDescData = protoimpl.X.CompressGZIP(file_seed_seed_proto_rawDescData)
	})
	return file_seed_seed_proto_rawDescData
}

var file_seed_seed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_seed_seed_proto_goTypes = []interface{}{
	(*SeedRequest)(nil),  // 0: SeedRequest
	(*SeedResponse)(nil), // 1: SeedResponse
}
var file_seed_seed_proto_depIdxs = []int32{
	0, // 0: Seed.Seed:input_type -> SeedRequest
	1, // 1: Seed.Seed:output_type -> SeedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seed_seed_proto_init() }
func file_seed_seed_proto_init() {
	if File_seed_seed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seed_seed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seed_seed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seed_seed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seed_seed_proto_goTypes,
		DependencyIndexes: file_seed_seed_proto_depIdxs,
		MessageInfos:      file_seed_seed_proto_msgTypes,
	}.Build()
	File_seed_seed_proto = out.File
	file_seed_seed_proto_rawDesc = nil
	file_seed_seed_proto_goTypes = nil
	file_seed_seed_proto_depIdxs = nil
}
