// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package seed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SeedClient is the client API for Seed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeedClient interface {
	Seed(ctx context.Context, in *SeedRequest, opts ...grpc.CallOption) (*SeedResponse, error)
}

type seedClient struct {
	cc grpc.ClientConnInterface
}

func NewSeedClient(cc grpc.ClientConnInterface) SeedClient {
	return &seedClient{cc}
}

var seedSeedStreamDesc = &grpc.StreamDesc{
	StreamName: "Seed",
}

func (c *seedClient) Seed(ctx context.Context, in *SeedRequest, opts ...grpc.CallOption) (*SeedResponse, error) {
	out := new(SeedResponse)
	err := c.cc.Invoke(ctx, "/Seed/Seed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeedService is the service API for Seed service.
// Fields should be assigned to their respective handler implementations only before
// RegisterSeedService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type SeedService struct {
	Seed func(context.Context, *SeedRequest) (*SeedResponse, error)
}

func (s *SeedService) seed(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Seed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Seed/Seed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Seed(ctx, req.(*SeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterSeedService registers a service implementation with a gRPC server.
func RegisterSeedService(s grpc.ServiceRegistrar, srv *SeedService) {
	srvCopy := *srv
	if srvCopy.Seed == nil {
		srvCopy.Seed = func(context.Context, *SeedRequest) (*SeedResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Seed not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "Seed",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Seed",
				Handler:    srvCopy.seed,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "seed/seed.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewSeedService creates a new SeedService containing the
// implemented methods of the Seed service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewSeedService(s interface{}) *SeedService {
	ns := &SeedService{}
	if h, ok := s.(interface {
		Seed(context.Context, *SeedRequest) (*SeedResponse, error)
	}); ok {
		ns.Seed = h.Seed
	}
	return ns
}

// UnstableSeedService is the service API for Seed service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableSeedService interface {
	Seed(context.Context, *SeedRequest) (*SeedResponse, error)
}
