// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: tracker/tracker.proto

package tracker

import (
	peer "github.com/dawidd6/p2p/peer"
	piece "github.com/dawidd6/p2p/piece"
	state "github.com/dawidd6/p2p/state"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AnnounceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TorrentSha256   string         `protobuf:"bytes,1,opt,name=torrent_sha256,json=torrentSha256,proto3" json:"torrent_sha256,omitempty"`
	DownloadedBytes uint64         `protobuf:"varint,2,opt,name=downloaded_bytes,json=downloadedBytes,proto3" json:"downloaded_bytes,omitempty"`
	UploadedBytes   uint64         `protobuf:"varint,3,opt,name=uploaded_bytes,json=uploadedBytes,proto3" json:"uploaded_bytes,omitempty"`
	TorrentPieces   []*piece.Piece `protobuf:"bytes,4,rep,name=torrent_pieces,json=torrentPieces,proto3" json:"torrent_pieces,omitempty"`
	TorrentState    state.State    `protobuf:"varint,5,opt,name=torrent_state,json=torrentState,proto3,enum=State" json:"torrent_state,omitempty"`
}

func (x *AnnounceRequest) Reset() {
	*x = AnnounceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracker_tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceRequest) ProtoMessage() {}

func (x *AnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceRequest.ProtoReflect.Descriptor instead.
func (*AnnounceRequest) Descriptor() ([]byte, []int) {
	return file_tracker_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *AnnounceRequest) GetTorrentSha256() string {
	if x != nil {
		return x.TorrentSha256
	}
	return ""
}

func (x *AnnounceRequest) GetDownloadedBytes() uint64 {
	if x != nil {
		return x.DownloadedBytes
	}
	return 0
}

func (x *AnnounceRequest) GetUploadedBytes() uint64 {
	if x != nil {
		return x.UploadedBytes
	}
	return 0
}

func (x *AnnounceRequest) GetTorrentPieces() []*piece.Piece {
	if x != nil {
		return x.TorrentPieces
	}
	return nil
}

func (x *AnnounceRequest) GetTorrentState() state.State {
	if x != nil {
		return x.TorrentState
	}
	return state.State_UNKNOWN
}

type AnnounceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []*peer.Peer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *AnnounceReply) Reset() {
	*x = AnnounceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tracker_tracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnounceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceReply) ProtoMessage() {}

func (x *AnnounceReply) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_tracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceReply.ProtoReflect.Descriptor instead.
func (*AnnounceReply) Descriptor() ([]byte, []int) {
	return file_tracker_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *AnnounceReply) GetPeers() []*peer.Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_tracker_tracker_proto protoreflect.FileDescriptor

var file_tracker_tracker_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x70, 0x65, 0x65, 0x72, 0x2f, 0x70, 0x65,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70, 0x69, 0x65, 0x63, 0x65, 0x2f,
	0x70, 0x69, 0x65, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe6,
	0x01, 0x0a, 0x0f, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x68,
	0x61, 0x32, 0x35, 0x36, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x6f, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x53, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x0e, 0x74,
	0x6f, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x69, 0x65, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x52, 0x0d, 0x74, 0x6f, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x50, 0x69, 0x65, 0x63, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x0d, 0x74, 0x6f,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x06, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x74, 0x6f, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x2c, 0x0a, 0x0d, 0x41, 0x6e, 0x6e, 0x6f, 0x75,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1b, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x05,
	0x70, 0x65, 0x65, 0x72, 0x73, 0x32, 0x37, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x12, 0x2c, 0x0a, 0x08, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x2e, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x20,
	0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x77,
	0x69, 0x64, 0x64, 0x36, 0x2f, 0x70, 0x32, 0x70, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tracker_tracker_proto_rawDescOnce sync.Once
	file_tracker_tracker_proto_rawDescData = file_tracker_tracker_proto_rawDesc
)

func file_tracker_tracker_proto_rawDescGZIP() []byte {
	file_tracker_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_tracker_tracker_proto_rawDescData)
	})
	return file_tracker_tracker_proto_rawDescData
}

var file_tracker_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tracker_tracker_proto_goTypes = []interface{}{
	(*AnnounceRequest)(nil), // 0: AnnounceRequest
	(*AnnounceReply)(nil),   // 1: AnnounceReply
	(*piece.Piece)(nil),     // 2: Piece
	(state.State)(0),        // 3: State
	(*peer.Peer)(nil),       // 4: Peer
}
var file_tracker_tracker_proto_depIdxs = []int32{
	2, // 0: AnnounceRequest.torrent_pieces:type_name -> Piece
	3, // 1: AnnounceRequest.torrent_state:type_name -> State
	4, // 2: AnnounceReply.peers:type_name -> Peer
	0, // 3: Tracker.Announce:input_type -> AnnounceRequest
	1, // 4: Tracker.Announce:output_type -> AnnounceReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tracker_tracker_proto_init() }
func file_tracker_tracker_proto_init() {
	if File_tracker_tracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tracker_tracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnounceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tracker_tracker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnounceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tracker_tracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_tracker_proto_msgTypes,
	}.Build()
	File_tracker_tracker_proto = out.File
	file_tracker_tracker_proto_rawDesc = nil
	file_tracker_tracker_proto_goTypes = nil
	file_tracker_tracker_proto_depIdxs = nil
}
