// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ClientClient is the client API for Client service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type clientClient struct {
	cc grpc.ClientConnInterface
}

func NewClientClient(cc grpc.ClientConnInterface) ClientClient {
	return &clientClient{cc}
}

var clientAddStreamDesc = &grpc.StreamDesc{
	StreamName: "Add",
}

func (c *clientClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var clientDeleteStreamDesc = &grpc.StreamDesc{
	StreamName: "Delete",
}

func (c *clientClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var clientListStreamDesc = &grpc.StreamDesc{
	StreamName: "List",
}

func (c *clientClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientService is the service API for Client service.
// Fields should be assigned to their respective handler implementations only before
// RegisterClientService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type ClientService struct {
	Add    func(context.Context, *AddRequest) (*AddResponse, error)
	Delete func(context.Context, *DeleteRequest) (*DeleteResponse, error)
	List   func(context.Context, *ListRequest) (*ListResponse, error)
}

func (s *ClientService) add(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/proto.Client/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *ClientService) delete(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/proto.Client/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *ClientService) list(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/proto.Client/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterClientService registers a service implementation with a gRPC server.
func RegisterClientService(s grpc.ServiceRegistrar, srv *ClientService) {
	srvCopy := *srv
	if srvCopy.Add == nil {
		srvCopy.Add = func(context.Context, *AddRequest) (*AddResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
		}
	}
	if srvCopy.Delete == nil {
		srvCopy.Delete = func(context.Context, *DeleteRequest) (*DeleteResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
		}
	}
	if srvCopy.List == nil {
		srvCopy.List = func(context.Context, *ListRequest) (*ListResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "proto.Client",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Add",
				Handler:    srvCopy.add,
			},
			{
				MethodName: "Delete",
				Handler:    srvCopy.delete,
			},
			{
				MethodName: "List",
				Handler:    srvCopy.list,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "pkg/proto/client.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewClientService creates a new ClientService containing the
// implemented methods of the Client service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewClientService(s interface{}) *ClientService {
	ns := &ClientService{}
	if h, ok := s.(interface {
		Add(context.Context, *AddRequest) (*AddResponse, error)
	}); ok {
		ns.Add = h.Add
	}
	if h, ok := s.(interface {
		Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	}); ok {
		ns.Delete = h.Delete
	}
	if h, ok := s.(interface {
		List(context.Context, *ListRequest) (*ListResponse, error)
	}); ok {
		ns.List = h.List
	}
	return ns
}

// UnstableClientService is the service API for Client service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableClientService interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
}
